package com.quantlab.risk.model;

public enum RiskDecision {
    APPROVE,
    APPROVED,
    APPROVE_REDUCED,
    REJECT,
    REJECTED_SIGNAL_SCORE,
    REJECTED_LOW_CONFIDENCE,
    REJECTED_SHORT_NOT_ALLOWED,
    ZERO_ALLOCATION,
    INSUFFICIENT_DATA,
    BLOCKED_BY_RISK_LIMIT,
    BLOCKED_BY_DATA_QUALITY,
    BLOCKED_BY_LIQUIDITY,
    BLOCKED_BY_CONCENTRATION,
    BLOCKED_BY_DRAWDOWN,
    BLOCKED_BY_MODEL_QUALITY
}
